apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: task-run
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dep-task 
  resources:
    inputs:
      - name: main
        resourceRef:
          name: main
