apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dep-task
  serviceAccountName: bashayr-docker-hub
spec:
  inputs:
      - name: main
        type: git
  steps: 
    - name: try 
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        pwd
        ls -gAhF
        echo "--------"
        ls -gAhF ../      
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(resource.inputs.main)/deploy-microserv-tkn/complete/complete.yaml" 
