apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-pipelinerun
spec:
  serviceAccountName: bashayr-docker-hub
  workspaces:
  - name: output # must match workspace name in the Task
    persistentVolumeClaim:
      claimName: kh-pvc-2 # this PVC must already exist
  pipelineRef:
    name: front-end-pipeline 
  resources:
    - name: user-resource
      resourceRef:
        name: user-resource
    - name: front-end-resource
      resourceRef:
        name: front-end-resource
#    - name: test-resource
#      resourceRef:
#        name: test-resource
