apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-pipelinerun
spec:
  serviceAccountName: bashayr-docker-hub
  params:
    - name: url
      value: $(params.repo-url)
  pipelineRef:
    name: parallel-pipeline 
