apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: payment-pipelinerun
spec:
  serviceAccountName: bashayr-docker-hub
  workspaces:
  - name: output # must match workspace name in the Task
    persistentVolumeClaim:
      claimName: kh-pvc-2 # this PVC must already exist
  pipelineRef:
    name: payment-pipeline
  resources:
    - name: payment-resource
      resourceRef:
        name: payment-resource 
