apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: queue-master-pipelinerun
spec:
  serviceAccountName: bashayr-docker-hub
  workspaces:
  - name: output # must match workspace name in the Task
    persistentVolumeClaim:
      claimName: kh-pvc-2 # this PVC must already exist
  pipelineRef:
    name: queue-master-pipeline
  resources:
    - name: queue-master-resource
      resourceRef:
        name: queue-master-resource 
