apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-catalogue-db
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-catalogue-db
  params:
  - name: IMAGE
    value: "bashayr/catalogue-db"
  resources:
    inputs:
    - name: catalogue-db-resource
      resourceRef:
        name: catalogue-db-resource
