apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-carts
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-carts
  params:
  - name: IMAGE
    value: "bashayr/carts"
  resources:
    inputs:
    - name: carts-resource
      resourceRef:
        name: carts-resource
