apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-user
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-user
  params:
  - name: IMAGE
    value: "bashayr/user"
  resources:
    inputs:
    - name: user-resource
      resourceRef:
        name: user-resource
