apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-payment
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-payment
  params:
  - name: IMAGE
    value: "bashayr/payment"
  resources:
    inputs:
    - name: payment-resource
      resourceRef:
        name: payment-resource
