build:
	docker build -t bashayr/shipping .
run:
	docker run --rm -it -p 8089:80 bashayr/shipping
sh:
	docker run --rm -it -p 8089:80 --entrypoint sh bashayr/shipping
docker-push:
	docker push bashayr/shipping
