kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: micro-role
rules:
- apiGroups: ["", "extensions", "apps","rbac.authorization.k8s.io"]
  resources: ["services","deployments", "deployments.apps", "replicasets", "pods","services", "endpoints", "pods","deployments","serviceaccounts", "clusterroles", "rolebindings", "configmaps", "pods/log","secrets"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: micro-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-role
subjects:
  - kind: ServiceAccount
    name: bashayr-docker-hub

