kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tutorial-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services","deployments", "deployments.apps", "replicasets", "pods","serviceaccounts", "clusterroles","rolebindings", "secrets", "namespaces"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tutorial-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tutorial-role
subjects:
  - kind: ServiceAccount
    name: bashayr-docker-hub

