apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: main
spec:
  type: git
  params:
    - name: revision
      value: dev
    - name: url
      value: https://github.com/BYAT/sockshop-microservices
