apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: front-end-resource
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/BYAT/sockshop-microservices
