apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: user-db-resource
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/BYAT/sockshop-microservices
