apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: carts-pipeline
spec:
  resources:
    - name: carts-resource
      type: git
    - name: user-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name: dockr-carts-pip # task 1
      taskRef:               
        name: dockr-carts
      params:
      - name: IMAGE
        value: "bashayr/carts"
      resources:
        inputs:
        - name: carts-resource
          resource: carts-resource
#---------------------dep-----------------------------
    - name: carts-pipe
      taskRef:               
        name: carts-dep-task
      runAfter:
        - dockr-carts-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-carts-pipe  # task 3: waiting task
      taskRef:            
        name: waiting-task 
      runAfter:
        - carts-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-carts-pipe  # task 4: test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-carts-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: prod-carts-pipe     # Task 5
      taskRef:               
        name: carts-dep-task
      runAfter:
        - test-carts-pipe 
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource

