apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: catalogue-pipeline
spec:
  resources: 
    - name: catalogue-resource
      type: git
    - name: catalogue-db-resource
      type: git
    - name: user-resource
      type: git
#    - name: test-resource
#      type: git
  tasks:
    - name:  dockr-catalogue-db-pip # task 1 build & push docker db 
      taskRef:              
        name: dockr-catalogue-db
      params:
      - name: IMAGE
        value: "bashayr/catalogue-db"
      resources:
        inputs:
        - name: catalogue-db-resource
          resource: catalogue-db-resource
#---------------------docker-----------------------------
    - name: dockr-catalogue-pip # task 2: build & push catalogue image
      taskRef:              
        name: dockr-catalogue
      runAfter:
        - dockr-catalogue-db-pip
      params:
      - name: IMAGE
        value: "bashayr/catalogue"
      resources:
        inputs:
        - name: catalogue-resource
          resource: catalogue-resource
#---------------------dep-----------------------------
    - name: catalogue-pipe     # task 3: deploy catalogue service
      taskRef:               
        name: catalogue-dep-task
      runAfter:
        - dockr-catalogue-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
#    - name: waiting-catalogue-pipe  # task 4: waiting task
#      taskRef:            
#        name: waiting-task 
#      runAfter:
#        - catalogue-pipe
#      params:
#      - name: NAMESPACE
#        value: "prod"
#      resources:
#        inputs:
#        - name: user-resource
#          resource: user-resource
##----------------------test----------------------------
#    - name: test-catalogue-pipe  # task 5: test task
#      taskRef:
#        name: test-task
#      runAfter:
#        - waiting-catalogue-pipe
#      resources:
#        inputs:
#        - name: test-resource
#          resource: test-resource
##-----------------------prod---------------------------
#    - name: catalogue-prod-pipe     # task 3: deploy catalogue service
#      taskRef:
#        name: catalogue-dep-task
#      runAfter:
#        - test-catalogue-pipe
#      params:
#      - name: NAMESPACE
#        value: "prod"
#      resources:
#        inputs:
#        - name: user-resource
#          resource: user-resource
#
