apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: catalogue-pipeline
spec:
  resources: 
    - name: catalogue-resource
      type: git
    - name: catalogue-db-resource
      type: git
    - name: user-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name:  dockr-catalogue-db-pip # task 1 build & push docker db 
      taskRef:              
        name: dockr-catalogue-db
      params:
      - name: IMAGE
        value: "bashayr/catalogue-db"
      resources:
        inputs:
        - name: catalogue-db-resource
          resource: catalogue-db-resource
#---------------------docker-----------------------------
    - name: dockr-catalogue-pip # task 2: build & push catalogue image
      taskRef:              
        name: dockr-catalogue
      runAfter:
        - dockr-catalogue-db-pip
      params:
      - name: IMAGE
        value: "bashayr/catalogue"
      resources:
        inputs:
        - name: catalogue-resource
          resource: catalogue-resource
#---------------------dep-----------------------------
    - name: catalogue-pipe     # task 3: deploy catalogue service
      taskRef:               
        name: catalogue-dep-task
      runAfter:
        - dockr-catalogue-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-catalogue-pipe  # task 4: waiting task
      taskRef:            
        name: waiting-catalogue-task 
      runAfter:
        - catalogue-pipe
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-pipe  # task 5: test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-catalogue-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: catalogue-prod-pipe     # task 3: deploy catalogue service
      taskRef:
        name: catalogue-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-carts--------------------------
    - name: prod-carts-pipe     
      taskRef:               
        name: carts-dep-task
      runAfter:
        - test-pipe 
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-front-end--------------------------
    - name: front-pipe-prod    
      taskRef:               
        name: front-end-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-orders--------------------------
    - name: ordes-prod-pipe     
      taskRef:
        name: orders-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-payment--------------------------
    - name: payment-prod-pipe     # task 3: deploy payment service
      taskRef:
        name: payment-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-queue-master--------------------------
    - name: queue-master-prod-pipe     
      taskRef:
        name: queue-master-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-shipping--------------------------
    - name: shipping-prod-pipe     
      taskRef:
        name: shipping-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-user--------------------------
    - name: user-pipe-prod     
      taskRef:               
        name: user-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
