apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: front-end-pipeline
spec:
  resources:
    - name: front-end-resource
      type: git
    - name: user-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name: dockr-front-end-pip
      taskRef:               # will start execution immediately
        name: dockr-front-end
      params:
      - name: IMAGE
        value: "bashayr/front-end"
      resources:
        inputs:
        - name: front-end-resource
          resource: front-end-resource
#---------------------dep-----------------------------
    - name: front-pipe
      taskRef:               #Task 2
        name: front-end-dep-task
      runAfter:
        - dockr-front-end-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-front-pipe  # task 3: waiting task
      taskRef:            
        name: waiting-front-end-task 
      runAfter:
        - front-pipe
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-pipe  # task 4: test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-front-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: front-pipe-prod     # Task 5
      taskRef:               
        name: front-end-dep-task
      runAfter:
        - test-pipe # later on i need to change the task with task 4
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-catalogue---------------------------
    - name: catalogue-prod-pipe     
      taskRef:
        name: catalogue-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-carts--------------------------
    - name: prod-carts-pipe     
      taskRef:               
        name: carts-dep-task
      runAfter:
        - test-pipe 
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-orders--------------------------
    - name: ordes-prod-pipe     
      taskRef:
        name: orders-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-payment--------------------------
    - name: payment-prod-pipe     # task 3: deploy payment service
      taskRef:
        name: payment-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-queue-master--------------------------
    - name: queue-master-prod-pipe     
      taskRef:
        name: queue-master-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-shipping--------------------------
    - name: shipping-prod-pipe     
      taskRef:
        name: shipping-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-user--------------------------
    - name: user-pipe-prod     
      taskRef:               
        name: user-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
