apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: front-end-pipeline
spec:
  resources:
    - name: front-end-resource
      type: git
  workspaces:
    - name: output
  tasks:
    - name: dockr-front-end-pip
      taskRef:               # will start execution immediately
        name: dockr-front-end
      params:
      - name: IMAGE
        value: "bashayr/front-end"
      resources:
        inputs:
        - name: front-end-resource
          resource: front-end-resource
    - name: front-pipe
      taskRef:               # will start execution immediately
        name: front-end-dep-task
      runAfter: 
        - dockr-front-end-pip
      workspaces:
        - name: output
          workspace: output

