apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: front-end-pipeline
spec:
  workspaces:
    - name: output
  tasks:
    - name: front-pipe
      taskRef:               # will start execution immediately
        name: front-end-dep-task
      workspaces:
        - name: output
          workspace: output

