apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  workspaces:
    - name: output
  resources: 
    - name: order-resource
      type: git
  tasks:
    - name: dockr-order-pip
      taskRef:
        name: dockr-order
      params:
      - name: IMAGE
        value: "bashayr/order"
      resources:
        inputs:
        - name: order-resource
          resource: order-resource
    - name: orders-pipe
      taskRef:               # will start execution immediately
        name: orders-dep-task
      runAfter:
        - dockr-order-pip
      workspaces:
        - name: output
          workspace: output
