apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: payment-pipeline
spec:
  resources: 
    - name: payment-resource
      type: git
    - name: user-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name: dockr-payment-pip
      taskRef:               # will start execution immediately
        name: dockr-payment
      params:
      - name: IMAGE
        value: "bashayr/payment"
      resources:
        inputs:
        - name: payment-resource
          resource: payment-resource
    - name: payment-pipe # task 2: deploy service
      taskRef:            
        name: payment-dep-task
      runAfter:
        - dockr-payment-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-payment-pipe  # task 4: waiting task
      taskRef:            
        name: waiting-task 
      runAfter:
        - payment-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-payment-pipe  # task 5: test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-payment-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: payment-prod-pipe     # task 3: deploy payment service
      taskRef:
        name: payment-dep-task
      runAfter:
        - test-payment-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
