apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: queue-master-pipeline
spec:
  resources: 
    - name: queue-master-resource
      type: git
    - name: user-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name: dockr-queue-master-pip
      taskRef:               
        name: dockr-queue-master
      params:
      - name: IMAGE
        value: "bashayr/queue-master"
      resources:
        inputs:
        - name: queue-master-resource
          resource: queue-master-resource
    - name: queue-master-pipe
      taskRef:               
        name: queue-master-dep-task
      runAfter:
        - dockr-queue-master-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-queue-master-pipe  # task 4: waiting task
      taskRef:            
        name: waiting-queue-master-task 
      runAfter:
        - queue-master-pipe
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-pipe  # task 4 : test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-queue-master-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: queue-master-prod-pipe     # task 5: deploy queue-master service
      taskRef:
        name: queue-master-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-catalogue---------------------------
    - name: catalogue-prod-pipe     
      taskRef:
        name: catalogue-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-carts--------------------------
    - name: prod-carts-pipe     
      taskRef:               
        name: carts-dep-task
      runAfter:
        - test-pipe 
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-front-end--------------------------
    - name: front-pipe-prod    
      taskRef:               
        name: front-end-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-orders--------------------------
    - name: ordes-prod-pipe     
      taskRef:
        name: orders-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-payment--------------------------
    - name: payment-prod-pipe     # task 3: deploy payment service
      taskRef:
        name: payment-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource

#-----------------------prod-shipping--------------------------
    - name: shipping-prod-pipe     
      taskRef:
        name: shipping-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-user--------------------------
    - name: user-pipe-prod     
      taskRef:               
        name: user-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
