apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: queue-master-pipeline
spec:
  workspaces:
    - name: output
  tasks:
    - name: queue-master-pipe
      taskRef:               # will start execution immediately
        name: queue-master-dep-task
      workspaces:
        - name: output
          workspace: output
