apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: shipping-pipeline
spec:
  resources: 
    - name: shipping-resource
      type: git
    - name: user-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name: dockr-shipping-pip
      taskRef:               # task 1
        name: dockr-shipping
      params:
      - name: IMAGE
        value: "bashayr/shipping"
      resources:
        inputs:
        - name: shipping-resource
          resource: shipping-resource
    - name: shipping-pipe #task 2
      taskRef:               
        name: shipping-dep-task
      runAfter:
        - dockr-shipping-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-shipping-pipe  # task 4: waiting task
      taskRef:            
        name: waiting-task 
      runAfter:
        - shipping-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-shipping-pipe  # task 5: test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-shipping-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: shipping-prod-pipe     # task 3: deploy shipping service
      taskRef:
        name: shipping-dep-task
      runAfter:
        - test-shipping-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
