apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: shipping-pipeline
spec:
  workspaces:
    - name: output
  resources: 
    - name: shipping-resource
      type: git
  tasks:
    - name: dockr-shipping-pip
      taskRef:               # task 1
        name: dockr-shipping
      params:
      - name: IMAGE
        value: "bashayr/shipping"
      resources:
        inputs:
        - name: shipping-resource
          resource: shipping-resource
    - name: shipping-pipe #task 2
      taskRef:               
        name: shipping-dep-task
      runAfter:
        - dockr-shipping-pip
      workspaces:
        - name: output
          workspace: output
