apiVersion: tekton.dev/v1beta1 
kind: Pipeline
metadata:
  name: user-pipeline
spec:
  resources: 
    - name: user-resource
      type: git
    - name: user-db-resource
      type: git
    - name: test-resource
      type: git
  tasks:
    - name: dockr-user-db-pip # task 1: build and push user db image
      taskRef:
        name: dockr-user-db
      params:
      - name: IMAGE
        value: "bashayr/user-db"
      resources:
        inputs:
        - name: user-db-resource
          resource: user-db-resource
#---------------------docker db-----------------------------
    - name: dockr-user-pip # task 2: build and push user image
      taskRef:      
        name: dockr-user
      runAfter:          
        - dockr-user-db-pip
      params:
      - name: IMAGE
        value: "bashayr/user"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#---------------------dep db-----------------------------
    - name: user-pipe   # task 3:
      taskRef:          
        name: user-dep-task
      runAfter:
        - dockr-user-pip
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------wait----------------------------
    - name: waiting-user-pipe  # task 3: waiting task
      taskRef:            
        name: waiting-user-task 
      runAfter:
        - user-pipe
      params:
      - name: NAMESPACE
        value: "test"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#----------------------test----------------------------
    - name: test-pipe  # task 4: test task
      taskRef:
        name: test-task
      runAfter:
        - waiting-user-pipe
      resources:
        inputs:
        - name: test-resource
          resource: test-resource
#-----------------------prod---------------------------
    - name: user-pipe-prod     # Task 5
      taskRef:               
        name: user-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-catalogue---------------------------
    - name: catalogue-prod-pipe     
      taskRef:
        name: catalogue-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-carts--------------------------
    - name: prod-carts-pipe     
      taskRef:               
        name: carts-dep-task
      runAfter:
        - test-pipe 
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-front-end--------------------------
    - name: front-pipe-prod    
      taskRef:               
        name: front-end-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-orders--------------------------
    - name: ordes-prod-pipe     
      taskRef:
        name: orders-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-payment--------------------------
    - name: payment-prod-pipe     # task 3: deploy payment service
      taskRef:
        name: payment-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-queue-master--------------------------
    - name: queue-master-prod-pipe     
      taskRef:
        name: queue-master-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
#-----------------------prod-shipping--------------------------
    - name: shipping-prod-pipe     
      taskRef:
        name: shipping-dep-task
      runAfter:
        - test-pipe
      params:
      - name: NAMESPACE
        value: "prod"
      resources:
        inputs:
        - name: user-resource
          resource: user-resource
