build:
	docker build -t bashayr/orders .
run:
	docker run --rm -it -p 8088:80 bashayr/orders
sh:
	docker run --rm -it -p 8088:80 --entrypoint sh bashayr/orders
docker-push:
	docker push bashayr/orders
