apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-catalogue
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-catalogue
  params:
  - name: IMAGE
    value: "bashayr/catalogue"
  resources:
    inputs:
    - name: catalogue-resource
      resourceRef:
        name: catalogue-resource
