apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-order
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-order
  params:
  - name: IMAGE
    value: "bashayr/order"
  resources:
    inputs:
    - name: order-resource
      resourceRef:
        name: order-resource
