apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-user-db
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-user-db
  params:
  - name: IMAGE
    value: "bashayr/user-db"
  resources:
    inputs:
    - name: user-db-resource
      resourceRef:
        name: user-db-resource
