apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner-shipping
spec:
  serviceAccountName: bashayr-docker-hub
  taskRef:
    name: dockr-shipping
  params:
  - name: IMAGE
    value: "bashayr/shipping"
  resources:
    inputs:
    - name: shipping-resource
      resourceRef:
        name: shipping-resource
