apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: catalogue-dep-task
  serviceAccountName: bashayr-docker-hub
spec:
  workspaces:
    - name: output
  steps: 
    - name: try 
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        pwd
        ls -gAhF
        echo "--------"
        ls -gAhF output/
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "output/deploy-microserv-tkn/services/catalogue-db-svc.yaml" 
        - "-f"
        - "output/deploy-microserv-tkn/services/catalogue-db-dep.yaml" 
        - "-f"
        - "output/deploy-microserv-tkn/services/catalogue-svc.yaml" 
        - "-f"
        - "output/deploy-microserv-tkn/services/catalogue-dep.yaml"
