apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: front-end-dep-task
  serviceAccountName: bashayr-docker-hub
spec:
  params:
  - name: NAMESPACE
  resources:
    inputs:
    - name: user-resource
      type: git
  steps: 
    - name: try 
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        pwd
        ls -gAhF
        echo "--------"
        ls -gAhF user-resource/
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/front-end-svc.yaml" 
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/front-end-dep.yaml"
        - "-n"
        - "$(params.NAMESPACE)"
