apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: front-end-dep-task
  serviceAccountName: bashayr-docker-hub
spec:
  steps: 
    - name: try 
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        pwd
        ls -gAhF
        echo "--------"
        ls -gAhF 
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(resources.inputs.main.path)/deploy-microserv-tkn/services/front-end-svc.yaml" 
        - "-f"
        - "$(resources.inputs.main.path)/deploy-microserv-tkn/services/front-end-dep.yaml"
        - "-f"
        - "$(resources.inputs.main.path)/deploy-microserv-tkn/ingress.yaml"
