apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: payment-dep-task
  serviceAccountName: bashayr-docker-hub
spec:
  params:
  - name: NAMESPACE
  resources:
    inputs:
    - name: user-resource
      type: git
  steps: 
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/payment-svc.yaml" 
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/payment-dep.yaml"
        - "-n"
        - "$(params.NAMESPACE)"

