apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: user-dep-task
  serviceAccountName: bashayr-docker-hub
spec:
  params:
  - name: NAMESPACE
  resources:
    inputs:
    - name: user-resource
      type: git
  steps: 
    - name: try 
      image: ubuntu  # contains bash
      script: |
        #!/usr/bin/env bash
        pwd
        echo "--------"
    - name: run-user-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/user-db-svc.yaml"
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/user-db-dep.yaml"
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/user-svc.yaml" 
        - "-f"
        - "user-resource/deploy-microserv-tkn/services/user-dep.yaml"
        - "-n"
        - "$(params.NAMESPACE)"
