apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: waiting-task
  serviceAccountName: bashayr-docker-hub
spec:
  params:
  - name: NAMESPACE
  resources:
    inputs:
    - name: user-resource
      type: git
  steps: 
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "wait" 
        - "--for=condition=Ready"
        - "pods"
        - "--all"
        - "-n"
        - "$(params.NAMESPACE)"
