apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: waiting-task
  serviceAccountName: bashayr-docker-hub
spec:
  params:
  - name: NAMESPACE
  resources:
    inputs:
    - name: user-resource
      type: git
  steps: 
    - name: waiting-front-end-rabbitmq
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "wait" 
        - "--for=condition=Ready"
        - "pods"
        - "--all"
        -  "-l" 
        - "name=rabbitmq"
        - "-n"
        - "$(params.NAMESPACE)"
    - name: waiting-front-end
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "wait"
        - "--for=condition=Ready"
        - "pods"
        - "--all"
        -  "-l"
        - "name=front-end"
        - "-n"
        - "$(params.NAMESPACE)"
