---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    name: payment
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: payment
