---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    name: user
