apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: front-task-run
  namespace: sock-shop
spec:
  serviceAccountName: bashayr-docker-hub
  workspaces:
  - name: output # must match workspace name in the Task
    persistentVolumeClaim:
      claimName: kh-pvc-2 # this PVC must already exist
  taskRef:
    name: front-end-dep-task
  timeout: 1h0m0s
